name: project_craft
description: My take on a Project planner.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cloud_firestore: ^4.8.1
  firebase_auth: ^4.6.3
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.4.0
  google_sign_in: ^6.1.4
  uuid: ^3.0.7

dev_dependencies:
  fake_cloud_firestore: ^2.4.1+1
  firebase_auth_mocks: ^0.11.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
